# ==============
# Nord Prompt
# ==============

command_timeout = 800
scan_timeout = 30

add_newline = false
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[character]
success_symbol = "[](#88c0d0)"
error_symbol = "[](#bf616a)"

[directory]
style = "bold #81a1c1"
read_only = " "
truncation_length = 3

[git_branch]
style = "bold #a3be8c"

[git_status]
style = "#d08770"
format = "[$all_status$ahead_behind]($style)"

[username]
style_root = "bold #bf616a"
style_user = "#8fbcbb"

[hostname]
style = "#5e81ac"

[cmd_duration]
style = "dimmed #ebcb8b"
min_time = 500
format = " [⏱ $duration]($style)"
