[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.cursor]
cursor = "0xD8DEE9"
text = "0x2E3440"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[font]
size = 14

[font.normal]
family = "hackGen"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0019"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001"
key = "Home"

[[keyboard.bindings]]
chars = "\u0005"
key = "End"

[[keyboard.bindings]]
chars = "\u000B"
key = "X"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "R"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0

[keyboard]
